# Generated by Django 4.2.2 on 2023-06-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_of_tech', '0003_remove_category_image_category_preview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='preview',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_of_tech.category'),
        ),
    ]
